### ISSUE TITLE
Clicking "Submit" causes new course entry box to appear

### ISSUE THREAD

**Issue by jkatofsky** [yingjie-xu/FindFinalDateMcGill#11]
When I click "Submit" on the site, on top of submitting my inputted courses, it also opens a new course input box as if I had also clicked "Add Course".

**Comment by yingjie-xu** [comment]
Hi, sorry about the confusion. It is now fixed and you can add a course by pressing the `arrow down` key. Also, you can still submit the form by pressing the `submit` button or pressing the `enter` key.
